### ISSUE TITLE
Show connected account name on general settings page

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/unofficial-convertkit#14]
To make it easier for users or their developer to determine what account the website is currently connected to.

**Comment by luukvankooten** [comment]
@dannyvankooten also with javascript?

**Comment by dannyvankooten** [comment]
JS or cached, but JS is less code after the connection check also uses JS so I vote JS. :)

Verstuurd vanaf mijn iPhone

**Comment by luukvankooten** [comment]
JS got my vote too.
